### PR TITLE
Allow PHPUnit 5 6 and Code coverage with PHP 7

### PR DESCRIPTION
**Pull request by remicollet**
Tested with PHPUnit 5.0.6

### CODE REVIEW

**Comment by remicollet** [comment]
Notice, because of composer.lock, people will still use same version.

This can raise issue in travis (but doesn't seems enabled on this repo)

Without composer.lock
users of php <= 5.5 will pull PHPUnit 4.8
users of php >= 5.6 will pull PHPUnit 5.0

**Comment by nicolaasuni** [comment]
I am not sure that using two different phpunit versions is a good idea as there could be a case when the test differs.

**Comment by remicollet** [comment]
Additional commit (not depend on 1st) allow to run code coverage with PHP7

**Comment by nicolaasuni** [comment]
The multiple phpunit versions issue has been fixed on the latest release.
Closing this as no longer relevant.

**Pull request closed without merging**
